### ISSUE TITLE
Link to JSON

### ISSUE THREAD

**Issue by Linell** [msawka/swaggerdoc#1]
From the README, on viewing the generated stuff

> In the JSON API input box at the top of the page, paste in the link to the JSON

I'm sure I'm missing something, but what is the right way to actually link to the JSON file that is generated?

**Comment by msawka** [comment]
If you download swagger-ui, you can [customize](https://github.com/swagger-api/swagger-ui#swaggerui) the index.html page and link it directly (so the Swagger loads on load of the page):

``` javascript
var swaggerUi = new SwaggerUi({
  url:"http://petstore.swagger.io/v2/swagger.json",
  dom_id:"swagger-ui-container"
});

swaggerUi.load();
```

Does that help?

**Comment by Linell** [comment]
Well, I meant that when I run the mix task, it generates a `/swagger` folder. What's the best way to get the `/swagger/swagger.json` file to link up to it? Just host it to some static server and link up?

**Comment by msawka** [comment]
Oh, gotcha.  Yep, I would just host it on a static apache2 or nginx server.  As an example, we're actually hosting the [OpenAperture Manager's](https://github.com/OpenAperture/manager) Swagger just on Github:  [api.json](https://raw.githubusercontent.com/OpenAperture/openaperture.github.io/master/swagger/manager/api.json).  I've been taking that raw url and pasting into swagger-ui when I want to review something.

**Comment by Linell** [comment]
Awesome, thank you!
