### ISSUE TITLE
Error converting Ecto types

### ISSUE THREAD

**Issue by rpip** [msawka/swaggerdoc#2]
Really helpful library!

When matching on Ecto date and time types, the Ecto data types are prefixed with colons which causes the compiler to throw a syntax error as it assumes them to be atoms or Erlang method calls.

Another related problem was that when gathering the routes from the Phoenix application's router, it throws an error about an undefined `__routes__` even though it accurately gets the router module. I realized this was due to the fact the Phoenix app wasn't loaded so I checked how the `phoenix.routes` mix task is implemented and added a fix which seems to have fixed the issue. And now the `mix swagger` command runs well :smile: 

BTW, I'm on Elixir 1.0 and Phoenix 1.0.3

Will be sending a PR soon.

**Comment by msawka** [comment]
https://github.com/msawka/swaggerdoc/pull/3
